trigger:
  tags:
    include:
      - refs/tags/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    vsce package
    npm install -g vsce
  displayName: 'npm install'

- script: |
    vsce publish -p $VS_CODE patch
  displayName: 'release'
