# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- checkout: self
  persistCredentials: true
  clean: true

- script: |
    npm install
    npm install -g vsce
  displayName: 'npm install'

- script: |
    npm version patch
    vsce package
    vsce publish -p $VS_CODE
  displayName: 'publish'

- script: |
    echo "git config --global user.email $GIT_EMAIL"
    echo "git config --global user.name $GIT_USER"

    git config --global user.email "$GIT_EMAIL"
    git config --global user.name "$GIT_USER"
    git push --tags
  displayName: 'release'